In [5]:
import numpy as np

In [1]:
image_size = 28 
input_channels = 1
output_channels = 3
filter_size = 3
no_of_filters1 = 32
no_of_filters2 = 64
learning_rate = 0.1

In [6]:
mean = 0
std = 0.5

conv_layer1_weights = np.random.normal(mean, std,(filter_size, filter_size, input_channels, no_of_filters1))
conv_layer1_biases = np.zeros((1, no_of_filters1))
conv_layer2_weights = np.random.normal(mean, std,(filter_size, filter_size, no_of_filters1, no_of_filters2))
conv_layer2_biases = np.zeros((1, no_of_filters2))

In [28]:
print(conv_layer1_weights)
print(conv_layer1_biases)
print(conv_layer2_weights)
print(conv_layer2_biases)

[[[[ 2.53190841e-01  3.15880636e-01  1.05687341e-01  5.49539489e-01
     2.36589031e-01  7.26492343e-01 -1.21177428e+00  4.17265283e-02
    -1.13199737e-02 -2.51231771e-02  4.62511433e-01 -4.82684872e-01
    -7.41035300e-01 -2.81235273e-01  1.60628419e-01  5.60792643e-01
    -1.18963203e-01 -3.41826492e-01  6.98207950e-01  1.63789521e+00
     7.19273118e-01  1.25441378e+00 -7.60972762e-01  3.00798701e-01
     7.01744415e-01  5.19646433e-01  2.10636179e-01 -3.59142658e-01
     1.61104292e-01  5.50679512e-02  3.76508750e-01  5.97307399e-01]]

  [[ 7.33654346e-01 -9.60086684e-02  7.65483581e-01 -4.62133288e-01
     5.82960066e-01 -2.02962321e-01 -1.78300275e-02  1.19550642e+00
     1.14819701e-01 -5.22138982e-01  7.74463074e-02  7.35238888e-01
     1.54099469e-01 -2.14768038e-01  3.13361838e-02 -1.72561054e-02
    -8.99301835e-01 -2.53429096e-01  4.37143526e-01 -3.02100446e-01
     1.24706464e+00  8.11565204e-01 -4.42670921e-01  2.09920596e-01
    -8.21719897e-01  9.70366110e-01  6.198197

In [20]:
def conv(X,w,b):
    return np.sum(np.multiply(w,X))+b

def conv_layer(image, filter, bias):
    m,row,col,channels = image.shape
    nf = filter.shape[3]
    new_image = np.zeros((m, row-filter_size+1, col-filter_size+1, nf))

    for i in range(m):
        img = image[i]
        for r in range(row-filter_size+1):
            for c in range(col-filter_size+1):
                x = img[r:r+filter_size, c:c+filter_size, :]
                for f in range(nf):
                    new_image[i,r,c,f] = conv(x,filter[:,:,:,f],bias[:,f])

    return new_image

In [29]:
image = np.random.randn(5,5,5,3)
filter = np.zeros((3,3,3,5))
bias = np.zeros((1, 5))

new_image = conv_layer(image,filter, bias)
print(new_image.shape)

(5, 3, 3, 5)


In [30]:
print(new_image[1])

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [39]:
def maxPool(image):
    count_images,row,col,channels = image.shape
    new_row=row//2
    new_col=col//2
    new_image=np.zeros([count_images,new_row,new_col,channels])

    for i in range(count_images):
        img=image[i]
        for r in range(new_row):
            for c in range(new_col):
                for d in range(channels):
                     new_image[i,r,c,d]=np.max(img[2*r:2*r+2,2*c:2*c+2,d])
    return new_image

In [49]:
img = np.random.randn(10,5,5,3)
new_image = maxPool(img)
print(new_image.shape)
print(img.shape)
print(new_image)

(1, 2, 2, 1)
(1, 4, 4, 1)
[[[[0.13118662]
   [0.63950899]]

  [[2.15287236]
   [0.79035155]]]]


In [51]:
def unPooling(image):
    count_image,row,col,channels=image.shape
    new_image=np.zeros((count_image,2*row,2*col,channels))
    for i in range(count_image):
        img=image[i]
        for r in range(row):
            for c in range(col):
                for d in range(channels):
                    new_image[i,2*r:2*r+2,2*c:2*c+2,d]=img[r,c,d]                
    return new_image

In [54]:
new_img = unPooling(new_image)
print(new_img.shape)
print(new_img)

(1, 4, 4, 1)
[[[[0.13118662]
   [0.13118662]
   [0.63950899]
   [0.63950899]]

  [[0.13118662]
   [0.13118662]
   [0.63950899]
   [0.63950899]]

  [[2.15287236]
   [2.15287236]
   [0.79035155]
   [0.79035155]]

  [[2.15287236]
   [2.15287236]
   [0.79035155]
   [0.79035155]]]]


In [60]:
image = np.random.randn(10,5,5,3)
m,row,col,channels = image.shape
pad = 2
image_pad = np.zeros((m, row+2*pad, col+2*pad, channels))
print(image_pad.shape)
image_pad[:,pad+1:row+pad+1,pad+1:col+pad+1,:] = image
print(image_pad)

(10, 9, 9, 3)
[[[[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   ...
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   ...
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   ...
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  ...

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   ...
   [ 1.00717021 -0.45060495 -0.08311577]
   [-0.49674258 -0.06408237  0.62388362]
  