In [3]:
import numpy as np

In [1]:
image_size = 28 
input_channels = 1
output_channels = 3
filter_size = 3
no_of_filters1 = 32
no_of_filters2 = 64
learning_rate = 0.1

In [6]:
mean = 0
std = 0.5

conv_layer1_weights = np.random.normal(mean, std,(filter_size, filter_size, input_channels, no_of_filters1))
conv_layer1_biases = np.zeros((1, no_of_filters1))
conv_layer2_weights = np.random.normal(mean, std,(filter_size, filter_size, no_of_filters1, no_of_filters2))
conv_layer2_biases = np.zeros((1, no_of_filters2))

In [9]:
fig = plt.figure(figsize=(8,3))

for i in range(10):
    ax = fig.add_subplot(2, 5, 1 + i, xticks=[], yticks=[])
    im = x_train[i]
    j = y_train[i].item()
    ax.set_title(class_names[j])
    plt.imshow(im)
plt.show()

NameError: name 'plt' is not defined

In [20]:
def conv(X,w,b):
    return np.sum(np.multiply(w,X))+b

def conv_layer(image, filter, bias):
    m,row,col,channels = image.shape
    nf = filter.shape[3]
    new_image = np.zeros((m, row-filter_size+1, col-filter_size+1, nf))

    for i in range(m):
        img = image[i]
        for r in range(row-filter_size+1):
            for c in range(col-filter_size+1):
                x = img[r:r+filter_size, c:c+filter_size, :]
                for f in range(nf):
                    new_image[i,r,c,f] = conv(x,filter[:,:,:,f],bias[:,f])

    return new_image

In [29]:
image = np.random.randn(5,5,5,3)
filter = np.zeros((3,3,3,5))
bias = np.zeros((1, 5))

new_image = conv_layer(image,filter, bias)
print(new_image.shape)

(5, 3, 3, 5)


In [30]:
print(new_image[1])

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [39]:
def maxPool(image):
    count_images,row,col,channels = image.shape
    new_row=row//2
    new_col=col//2
    new_image=np.zeros([count_images,new_row,new_col,channels])

    for i in range(count_images):
        img=image[i]
        for r in range(new_row):
            for c in range(new_col):
                for d in range(channels):
                     new_image[i,r,c,d]=np.max(img[2*r:2*r+2,2*c:2*c+2,d])
    return new_image

In [49]:
img = np.random.randn(10,5,5,3)
new_image = maxPool(img)
print(new_image.shape)
print(img.shape)
print(new_image)

(1, 2, 2, 1)
(1, 4, 4, 1)
[[[[0.13118662]
   [0.63950899]]

  [[2.15287236]
   [0.79035155]]]]


In [51]:
def unPooling(image):
    count_image,row,col,channels=image.shape
    new_image=np.zeros((count_image,2*row,2*col,channels))
    for i in range(count_image):
        img=image[i]
        for r in range(row):
            for c in range(col):
                for d in range(channels):
                    new_image[i,2*r:2*r+2,2*c:2*c+2,d]=img[r,c,d]                
    return new_image

In [54]:
new_img = unPooling(new_image)
print(new_img.shape)
print(new_img)

(1, 4, 4, 1)
[[[[0.13118662]
   [0.13118662]
   [0.63950899]
   [0.63950899]]

  [[0.13118662]
   [0.13118662]
   [0.63950899]
   [0.63950899]]

  [[2.15287236]
   [2.15287236]
   [0.79035155]
   [0.79035155]]

  [[2.15287236]
   [2.15287236]
   [0.79035155]
   [0.79035155]]]]


In [2]:
image = np.random.randn(10,5,5,3)
m,row,col,channels = image.shape
pad = 2
image_pad = np.zeros((m, row+2*pad, col+2*pad, channels))
print(image_pad.shape)
image_pad[:,pad+1:row+pad+1,pad+1:col+pad+1,:] = image
print(image_pad)

NameError: name 'np' is not defined

In [4]:
image = np.random.randn(10,5,5,3)
image.shape

(10, 5, 5, 3)

In [6]:
a = np.zeros(image.shape)
print(a.shape)

(10, 5, 5, 3)


In [7]:
def Loss(input, output):
    count, row, col, channel = input.shape
    loss = np.zeros((1,channel))
    for i in range(count):
        img = input[i]
        img2 = output[i]
        for d in range(channel):
            for r in range(row):
                for c in range(col):
                    a = img[r, c, d]
                    b = img2[r, c, d]
                    loss[0,d] += (float(a)-float(b))*(float(a)-float(b))
    loss = loss/(row*col*count)
    return loss

In [4]:
import numpy as np
a = np.ones((5,3,3,3))
b = np.zeros((5,3,3,3))

In [10]:
print(Loss(a,b))

[[1. 1. 1.]]


In [13]:
print(b[0,0,0,0].type)

AttributeError: 'numpy.float64' object has no attribute 'type'

In [17]:
3.0*2

6.0